/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule City_item.graphql
 * @generated SignedSource<<6d1fd4ced0cc54a2dd6cd2e077138faa>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type City_item = {|
  +_id: number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "City_item",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "_id",
      "storageKey": null
    }
  ],
  "type": "City"
};

module.exports = fragment;
