/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule city_item.graphql
 * @generated SignedSource<<57f4b42c179d0d818326ad187880a6e8>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type city_item = {|
  +_id: number;
  +lat: ?number;
  +lng: ?number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "city_item",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "_id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "lat",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "lng",
      "storageKey": null
    }
  ],
  "type": "City"
};

module.exports = fragment;
