/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule mapQuery.graphql
 * @generated SignedSource<<e7289aecc0a9a135727f865ec423b456>>
 * @relayHash 94a6180db9dae1c2be959e2838b506b1
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query mapQuery {
  cities {
    ...city_item
  }
}

fragment city_item on City {
  _id
  lat
  lng
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "mapQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "City",
        "name": "cities",
        "plural": true,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "city_item",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "mapQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "mapQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "City",
        "name": "cities",
        "plural": true,
        "selections": [
          {
            "kind": "InlineFragment",
            "type": "City",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "_id",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "lat",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "lng",
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query mapQuery {\n  cities {\n    ...city_item\n  }\n}\n\nfragment city_item on City {\n  _id\n  lat\n  lng\n}\n"
};

module.exports = batch;
