/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule mapQuery.graphql
 * @generated SignedSource<<98bcaf01666163f322af95c81522b09d>>
 * @relayHash bc2dae601bcec850cb7d820db2e301b5
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query mapQuery {
  cities {
    lat
    lng
    ...City_item
  }
}

fragment City_item on City {
  _id
  todo {
    text
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "mapQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "City",
        "name": "cities",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lat",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lng",
            "storageKey": null
          },
          {
            "kind": "FragmentSpread",
            "name": "City_item",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "mapQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "mapQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "City",
        "name": "cities",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lat",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lng",
            "storageKey": null
          },
          {
            "kind": "InlineFragment",
            "type": "City",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "_id",
                "storageKey": null
              },
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "ToDo",
                "name": "todo",
                "plural": true,
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "text",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query mapQuery {\n  cities {\n    lat\n    lng\n    ...City_item\n  }\n}\n\nfragment City_item on City {\n  _id\n  todo {\n    text\n  }\n}\n"
};

module.exports = batch;
