/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule mapQuery.graphql
 * @generated SignedSource<<9d5298a3779c1c1c10d97ee582259a8c>>
 * @relayHash 08055be235ecfcc31334e7235824101e
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query mapQuery {
  cities {
    _id
    lat
    lng
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "mapQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "City",
        "name": "cities",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "_id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lat",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lng",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "mapQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "mapQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "City",
        "name": "cities",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "_id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lat",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "lng",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query mapQuery {\n  cities {\n    _id\n    lat\n    lng\n  }\n}\n"
};

module.exports = batch;
