/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Cities_city.graphql
 * @generated SignedSource<<4602662e251d23323cd41e2895a47019>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Cities_city = {|
  +id: number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Cities_city",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    }
  ],
  "type": "City"
};

module.exports = fragment;
