/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule CreateToDoMutation.graphql
 * @generated SignedSource<<2be241c5b494d4e965fa930caa90eb97>>
 * @relayHash 9424acf8de937dd9cdf99124ccbb39f8
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type ToDoInput = {
  city_id?: ?number;
  text?: ?string;
};

export type CreateToDoMutationResponse = { };
*/


/*
mutation CreateToDoMutation(
  $input: ToDoInput!
) {
  createToDo(input: $input) {
    ...ToDo
  }
}

fragment ToDo on ToDo {
  text
  likes
  _id
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "ToDoInput!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "CreateToDoMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "ToDoInput"
          }
        ],
        "concreteType": "ToDo",
        "name": "createToDo",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "ToDo",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "CreateToDoMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "ToDoInput!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "CreateToDoMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "ToDoInput"
          }
        ],
        "concreteType": "ToDo",
        "name": "createToDo",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "text",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "likes",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "_id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation CreateToDoMutation(\n  $input: ToDoInput!\n) {\n  createToDo(input: $input) {\n    ...ToDo\n  }\n}\n\nfragment ToDo on ToDo {\n  text\n  likes\n  _id\n}\n"
};

module.exports = batch;
