/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule ToDoList_todo.graphql
 * @generated SignedSource<<39500c7cd1ec2bdbbbe3fd94904a45f5>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type ToDoList_todo = {|
  +todo: ?{|
    +edges: ?$ReadOnlyArray<?{|
      +node: ?{| |};
    |}>;
  |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "first",
      "type": "Int"
    },
    {
      "kind": "RootArgument",
      "name": "last",
      "type": "String"
    }
  ],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": "first",
        "cursor": "last",
        "direction": "forward",
        "path": [
          "todo"
        ]
      }
    ]
  },
  "name": "ToDoList_todo",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": "todo",
      "args": null,
      "concreteType": "ToDoConnection",
      "name": "__ToDoConnection_todo_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "ToDoEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "ToDo",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "FragmentSpread",
                  "name": "ToDo",
                  "args": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "City"
};

module.exports = fragment;
