/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule ToDo.graphql
 * @generated SignedSource<<67cd8e79ba2120211263da51beff0b4d>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type ToDo = {|
  +text: ?string;
  +likes: ?number;
  +_id: number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "ToDo",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "text",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "likes",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "_id",
      "storageKey": null
    }
  ],
  "type": "ToDo"
};

module.exports = fragment;
